columns:
  - ../../wall_columns/internal.standard/cut_stone_wall_columns
  - internal.standard
  - stl
columns_90:
  - ../../wall_columns/90degrees.internal.standard/cut_stone_wall_columns
  - 90degrees.internal.standard
  - stl
columns_corner:
  - ../../corner_columns/internal.standard/cut_stone_corner_column
  - internal.standard.stl
back_length:
  1: 0
  2: 2
  3: 5
  4: 7
result:
  - cut_stone_corner_back
  - internal.standard.stl
external: false
inverse: false
