columns:
  - ../../wall_columns/external.standard/cut_stone_wall_columns
  - external.standard
  - stl
columns_90:
  - ../../wall_columns/90degrees.external.standard/cut_stone_wall_columns
  - 90degrees.external.standard
  - stl
columns_corner:
  - ../../corner_columns/external.standard/cut_stone_corner_column
  - external.standard.stl
back_length:
  1: 1
  2: 3
  3: 6
  4: 8
result:
  - cut_stone_corner_back
  - external.standard.stl
external: true
inverse: false
